module.exports = {
  // Like the one described here: https://swagger.io/specification/#infoObject
  info: {
    title: "Podcast Review API",
    version: "1.0.0",
    description: "Test Podcast Review API with autogenerated swagger doc",
  },
  apis: ["src/**/*.ts"],
};
